---
language: python
services:
  - docker
env:
  global:
    - ROLE_NAME: visual_studio_code
  matrix:
    - MOLECULE_DISTRO: ubuntu:artful
    - MOLECULE_DISTRO: ubuntu:bionic
    - MOLECULE_DISTRO: ubuntu:cosmic
    - MOLECULE_DISTRO: ubuntu:xenial
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule docker
before_script:
  - cd ../
  - mv ansible-role-${ROLE_NAME//_/-} rgibert.$ROLE_NAME
  - cd rgibert.$ROLE_NAME
script:
  - molecule test
