---
- block:

    - name: create target download path
      file:
        state: directory
        path: "{{ visual_studio_code_rpm_dl_path }}"

    - name: download package
      get_url:
        url: "{{ visual_studio_code_repo_root}}/linux-rpm-{{ visual_studio_code_arch }}/stable"
        dest: "{{ visual_studio_code_rpm_dl_path }}"

    - name: install package
      yum:
        name: "{{ visual_studio_code_rpm_dl_path }}/*.rpm"
        state: present

  become: true
  become_user: root
